set_property SRC_FILE_INFO {cfile:C:/Users/carl/fpga/project_6/project_6.srcs/constrs_1/new/topDesign.xdc rfile:../../../project_6.srcs/constrs_1/new/topDesign.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P17 } [get_ports clk_i]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G2 } [get_ports en_seg[0]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C2 } [get_ports en_seg[1]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C1 } [get_ports en_seg[2]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H1 } [get_ports en_seg[3]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G1 } [get_ports en_seg[4]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F1 } [get_ports en_seg[5]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E1 } [get_ports en_seg[6]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G6 } [get_ports en_seg[7]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B4 } [get_ports led_o_l[6]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A4 } [get_ports led_o_l[5]]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A3 } [get_ports led_o_l[4]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B1 } [get_ports led_o_l[3]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A1 } [get_ports led_o_l[2]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B3 } [get_ports led_o_l[1]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B2 } [get_ports led_o_l[0]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D4 } [get_ports led_o_r[6]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E3 } [get_ports led_o_r[5]]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D3 } [get_ports led_o_r[4]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F4 } [get_ports led_o_r[3]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F3 } [get_ports led_o_r[2]]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E2 } [get_ports led_o_r[1]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D2 } [get_ports led_o_r[0]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U4 } [get_ports S4]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V1 } [get_ports S3]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R15} [get_ports S2]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R17} [get_ports S1]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R11} [get_ports S0]
