set_property SRC_FILE_INFO {cfile:C:/Users/carl/fpga/hexseg8/hexseg8.srcs/constrs_1/new/hexseg8.xdc rfile:../../../hexseg8.srcs/constrs_1/new/hexseg8.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P17 } [get_ports clk_i]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R11 } [get_ports rst_n_i]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R1 } [get_ports sw_i[0]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N4 } [get_ports sw_i[1]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M4 } [get_ports sw_i[2]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R2 } [get_ports sw_i[3]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P2 } [get_ports sw_i[4]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P3 } [get_ports sw_i[5]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P4 } [get_ports sw_i[6]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P5 } [get_ports sw_i[7]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G2 } [get_ports en[0]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C2 } [get_ports en[1]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C1 } [get_ports en[2]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H1 } [get_ports en[3]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G1 } [get_ports en[4]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F1 } [get_ports en[5]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E1 } [get_ports en[6]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G6 } [get_ports en[7]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B4 } [get_ports led_o_l[6]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A4 } [get_ports led_o_l[5]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A3 } [get_ports led_o_l[4]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B1 } [get_ports led_o_l[3]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A1 } [get_ports led_o_l[2]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B3 } [get_ports led_o_l[1]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B2 } [get_ports led_o_l[0]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D4 } [get_ports led_o_r[6]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E3 } [get_ports led_o_r[5]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D3 } [get_ports led_o_r[4]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F4 } [get_ports led_o_r[3]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F3 } [get_ports led_o_r[2]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E2 } [get_ports led_o_r[1]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D2 } [get_ports led_o_r[0]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H2 } [get_ports dot]
