set_property SRC_FILE_INFO {cfile:C:/Users/carl/fpga/project_3/project_3.srcs/constrs_1/new/seqdetecter.xdc rfile:../../../project_3.srcs/constrs_1/new/seqdetecter.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P17 } [get_ports clk_i]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R15 } [get_ports rst_i]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U4 } [get_ports set_i]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P5 } [get_ports data_i[7]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P4 } [get_ports data_i[6]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P3 } [get_ports data_i[5]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P2 } [get_ports data_i[4]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R2 } [get_ports data_i[3]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M4 } [get_ports data_i[2]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N4 } [get_ports data_i[1]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R1 } [get_ports data_i[0]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K2} [get_ports detect_o]
